name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.23.0",1.24.2]
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}
      - run: go test
      - run: go run math.go